### Get all the movies
GET http://localhost:3001/api/movies

### Get a movie by id (first movie)
GET http://localhost:3001/api/movies/4aa002ed-bb13-11ee-92db-5065f33370da

### Get all the movies by genre
GET http://localhost:3001/api/movies?genre=drama

### Post a movie
POST http://localhost:3001/api/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "rate": 9.2,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/144441949_max.jpg",
  "genre": [
    "Crime", "Drama"
  ]
}

### Update a movie (the posted one)
PATCH http://localhost:3001/api/movies/4aa002ed-bb13-11ee-92db-5065f33370da
Content-Type: application/json

{
  "year": 1998
}

### Delete a movie (the posted one)
DELETE http://localhost:3001/api/movies/65867e2b-bb13-11ee-92db-5065f33370da
